import Foundation

enum CloudKitRecordType {
    static let trip = "Trip"
    static let milestone = "Milestone"
    static let itinerary = "Itinerary"
    static let costs = "Costs"
    static let checklist = "Checklist"
}

enum CloudKitFieldKey {
    static let tripId = "tripId"
    static let startCity = "startCity"
    static let endCity = "endCity"
    static let startDate = "startDate"
    static let endDate = "endDate"
    static let vehicleName = "vehicleName"
    static let fuelType = "fuelType"
    static let mileageKmPerLiter = "mileageKmPerLiter"
    static let fuelPricePerLiter = "fuelPricePerLiter"
    static let maxKmPerDay = "maxKmPerDay"
    static let avoidNightDriving = "avoidNightDriving"
    static let breakEveryHours = "breakEveryHours"
    static let breakDurationMinutes = "breakDurationMinutes"
    static let adults = "adults"
    static let kids = "kids"
    static let foodType = "foodType"
    static let dailyFoodBudget = "dailyFoodBudget"
    static let lodgingBudget = "lodgingBudget"
    static let isProUser = "isProUser"

    static let milestoneId = "milestoneId"
    static let itineraryId = "itineraryId"
    static let costsId = "costsId"
    static let checklistId = "checklistId"
    static let tripReference = "tripId"
    static let milestoneType = "type"
    static let name = "name"
    static let mustDo = "mustDo"
    static let timeWindowStart = "timeWindowStart"
    static let timeWindowEnd = "timeWindowEnd"
    static let notes = "notes"
    static let sortOrder = "sortOrder"
    static let source = "source"
    static let days = "days"
    static let lastUpdated = "lastUpdated"
    static let fuelCost = "fuelCost"
    static let foodCost = "foodCost"
    static let lodgingCost = "lodgingCost"
    static let totalCost = "totalCost"
    static let title = "title"
    static let items = "items"
}
